
name: Deploy Maven Project to ECS (Tomcat)

on:
  push:
    branches: main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' 

    - name: Build with Maven
      run: mvn clean package

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::204615365209:role/tony-role
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 204615365209.dkr.ecr.us-east-1.amazonaws.com
        docker build -t my-repo .
        docker tag my-repo:latest 204615365209.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
        docker push 204615365209.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster maven-cluster \
          --service maven-project-service \
          --force-new-deployment

